all :
	make -C ../../ all

clists :
	make -C ../../ MAIN="src/gui/giant-clists.adb" all

gui_test :
	make -C ../../ MAIN="src/gui/giant-gui_test.adb" EXEC="src/gui/gui_test" all

.PHONY : all gui_test
