settings :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-settings all

vectors :
	make -C ../../ MAIN=src/vis/giant-vectors all

vis :
	make -C ../../ MAIN=src/vis/giant-vis all

vis_data :
	make -C ../../ MAIN=src/vis/giant-vis_data all

mini_maps :
	make -C ../../ MAIN=src/vis/giant-mini_maps all

graph_widgets :
	make -C ../../ MAIN=src/vis/giant-graph_widgets all

handlers :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-handlers all

notifications :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-notifications all

drawing :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-drawing all

positioning :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-positioning all

states :
	make -C ../../ MAIN=src/vis/giant-graph_widgets-states all

all : 
	make -C ../../ all

.PHONY : all test
