gsl :
	#make -C generated
	make -C ../../ MAIN="src/gsl/giant-gsl-types"
	make -C ../../ MAIN="src/gsl/giant-gsl-syntax_tree"
	make -C ../../ MAIN="src/gsl/giant-gsl-compilers"
	make -C ../../ MAIN="src/gsl/giant-gsl-interpreters"
	make -C ../../ MAIN="src/gsl/parser_test" EXEC="src/gsl/parser_test"
	make -C ../../ MAIN="src/gsl/gsl_test" EXEC="src/gsl/gsl_test"
	make -C ../../ MAIN="src/gsl/gsl_test_evolution" EXEC="src/gsl/test"
