all : 
	make -C ../../ all

merging_iterators :
	make -C ../../ MAIN=src/utils/giant-merging_iterators all

simple_priority_queues :
	make -C ../../ MAIN=src/utils/giant-simple_priority_queues all

fixed_priority_queues :
	make -C ../../ MAIN=src/utils/giant-fixed_priority_queues all

evolutions :
	make -C ../../ MAIN=src/utils/giant-evolutions all

.PHONY : all
